name: rima
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.26.4
  - scipy=1.16.1
  - scikit-learn=1.3.0
  - pandas=1.5.3
  - matplotlib=3.10.5
  - pillow
  - tqdm
  - pip:
    - torch==2.5.1+cu121
    - torchvision==0.20.1
    - torchaudio==2.5.1+cu121
    - torchmetrics==1.3.0
    - jax==0.7.0
    - jaxlib==0.7.0
    - jaxopt==0.8.3
    - jaxtyping==0.3.2
    - einops==0.8.0
    - flax==0.10.2
    - equinox==0.13.0
    - lineax==0.0.8
    - -e perturbot/
    - -e ott-local/ 